export const StoreConf = {
  payType: [
    { name: '가평군', value: 'GAPYUNG' },
    { name: '고양시', value: 'GOYANG' },
    { name: '과천시', value: 'GYACHUN' },
    { name: '광명시', value: 'GYANGMYUNG' },
    { name: '광주시', value: 'GYANGJU' },
    { name: '구리시', value: 'GURI' },
    { name: '군포시', value: 'GUNPO' },
    { name: '김포시', value: 'GIMPO' },
    { name: '남양주시', value: 'NAMYANGJU' },
    { name: '동두천시', value: 'DONDUCHUN' },
    { name: '부천시', value: 'BOOCHUN' },
    { name: '성남시', value: 'SUNGNAM' },
    { name: '수원시', value: 'SUWON' },
    { name: '시흥시', value: 'SIHEUNG' },
    { name: '안산시', value: 'ANSAN' },
    { name: '안성시', value: 'ANSEONG' },
    { name: '안양시', value: 'ANYANG' },
    { name: '양주시', value: 'YANGJU' },
    { name: '양평시', value: 'YANGPYUNG' },
    { name: '여주시', value: 'YEOJU' },
  ],

  storeType: [
    { name: '전체', value: 'ALL' },
    { name: '일반휴게음식', value: 'RESTAURANT' },
    { name: '의류', value: 'CLOTHES' },
    { name: '숙박업', value: 'LODGE' },
    { name: '유통업', value: 'MART' },
    { name: '음료식품', value: 'DRINK' },
    { name: '의원', value: 'ClINIC' },
    { name: '연료판매점', value: 'GASSTATION' },
  ],
}
